name: Send Emails

on:
  schedule:
    - cron: "0 22 */2 * *"
  workflow_dispatch:

jobs:
  send_emails:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install smtplib

    - name: Send Emails
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python send_emails.py
